name: Docker CI + Sync to Hugging Face

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build Docker Image (No Push)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: kamaleshbaskaran/simple-rag:latest

  sync-to-hub:
    name: Sync to Hugging Face Hub
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Configure Git and Sync with Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config user.email "kamalehsbaskran4310@gmail.com"
          git config user.name "Kamalesh"
          git remote add hf https://Kamaleshbaskaran:${HF_TOKEN}@huggingface.co/spaces/Kamaleshbaskaran/test-rag
          git fetch hf main
          git rebase hf/main
          git push hf HEAD:main --force
